// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbApJb6FcgREVQN0bzD3O8NlNWwTZgOuE',
    appId: '1:608750429569:web:134f5f76948c323abf3480',
    messagingSenderId: '608750429569',
    projectId: 'pcps2024-5df2a',
    authDomain: 'pcps2024-5df2a.firebaseapp.com',
    databaseURL: 'https://pcps2024-5df2a-default-rtdb.firebaseio.com',
    storageBucket: 'pcps2024-5df2a.appspot.com',
    measurementId: 'G-1XT1Z2J3YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxX2paW29zHGR-sFs8iWrJ3h4gvO2Ok94',
    appId: '1:608750429569:android:2c4afabc364e186bbf3480',
    messagingSenderId: '608750429569',
    projectId: 'pcps2024-5df2a',
    databaseURL: 'https://pcps2024-5df2a-default-rtdb.firebaseio.com',
    storageBucket: 'pcps2024-5df2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvb8-w2xq66FITLPHl6gFav0Hi_8yCQ7o',
    appId: '1:608750429569:ios:47445666b4c7b2c9bf3480',
    messagingSenderId: '608750429569',
    projectId: 'pcps2024-5df2a',
    databaseURL: 'https://pcps2024-5df2a-default-rtdb.firebaseio.com',
    storageBucket: 'pcps2024-5df2a.appspot.com',
    iosBundleId: 'com.pcps.flutterprojectlab1.lab1',
  );
}
